<?php require("../inc/top.php"); 
?>
		<div id="main">
			<?php require("../inc/subnav_sea.php"); ?>
			<h1>Sea Kayaking Safety</h1>
			<h2>Ocean Touring</h2>
			<h3>Part 1: Discussion and Classification</h3>
			<p>A) Skills and Equipment: The skills and equipment required for safe ocean touring have considerable overlap with those required for whitewater boating, but there are some important differences. The following discussion, though not exhaustive, gives some examples of these differences.</p>
			<p>1. Equipment: Sea kayaks are designed for efficient travel in a straight line, not for ease of turning. They are also designed with load carrying ability in mind. To accommodate the higher speed at which a sea kayak is generally paddled and need to stow gear in the boat, the sea kayak paddle is longer than a whitewater paddle. Sea kayakers need to dress for cold water immersion, but this must often be balanced with the likelihood of a capsize and the expected air temperatures, since overheating can be a problem in the warm months. When in doubt, the sea kayaker should dress for cold water immersion, since it can be very difficult to put on clothing if the conditions get difficult. Sea kayakers need some means of stabilizing their boat for reentry after a capsize and wet exit. This is one of the most important differences from whitewater kayaking, since whitewater kayakers almost never need to reenter their boats in the water after a wet exit.</p>
			<p>2. Skills: Since sea kayakers may find themselves far from shore, it is extremely important that the sea kayaker know how to recover from a capsize and wet exit. On a river, rescue from shore is often a possibility, and it is often the case that the capsized paddler washes out of the difficult spot into easier conditions. On the ocean, the conditions which caused a capsize will often be there after the capsize, and may not lessen for hours or even days. River kayakers often paddle in conditions which test their limits, with the result that they often practice their roll in realistic conditions. Sea kayakers may only rarely encounter conditions which test their limits, with the result that their roll is seldom practiced in realistic conditions. The result is that many sea kayakers do not have reliable rolling skills. When they do encounter conditions which test their limits, the situation is generally quite dangerous, since the consequences of a capsize in conditions near the limits of a paddler's ability may be severe. For this reason, although proficiency in the eskimo roll is strongly encouraged, it is not sufficient. Sea kayakers need to know how to recover unassisted from a capsize and wet exit, without going ashore. They also need to be familiar with techniques for assisting another kayakers to reenter their boat after a wet exit.</p>
			<p>B) Classification of Sea Kayak Trips: Classification of ocean trips is somewhat different than classification of river trips. For example, the expected difficulty of a river is usually well defined if the flow rate is known. On the ocean, this is not usually the case, since conditions on the ocean are very strongly influenced by the weather conditions encountered. The same stretch of water can be flat calm and glassy smooth one day and a maelstrom the next. In fact, the change can occur within minutes or even seconds. For this reason it is difficult to rate ocean trips in the same way that river trips are rated. The ratings given to an ocean trip must consider the potential for hazardous conditions, and the difficulty of escaping from them if they occur. The UKC uses the following rating system.</p>
			<p>Visit: <a href="seakayaking/sea_rating.php">Sea Kayak Trip Rating Scale</a></p>
			<p>Paddling speed: Trip announcements will include an estimate of the planned paddling speed for the trip. Slow = about 2 knots; Medium = 2.5-3.5 knots; Fast = over 3.5 knots.</p>
			<p>1. SK II trips are suitable for beginners who have some experience paddling in the lake. One may expect slightly rougher conditions for SK II+ trips. SK II+ trips are suitable for advanced beginners, usually those who have paddled on an SK II trip or two and can control their boat in light to moderate wind (5-10 knots) and small waves (~1 foot). As usual, the number of novice paddlers will depend on an appropriate number of experienced paddlers. Paddlers must have practiced re-entry techniques for any type of SK II trip and should be comfortable paddling approximately 10 miles without assisting winds or current.</p>
			<p>2. SK III trips are suitable for intermediate paddlers. It is advisable that paddlers have previous SK II experience. For an SK III trip, a paddler should be able to control their boat in moderate wind (~10 knots), handle small wind waves (1-2 feet), paddle at the designated trip speed. SK III trips are usually longer and require more endurance than SK II trips. The ability to paddle 15 or more miles a day, preferably over several days, is recommended. Paddlers must have practiced re-entry techniques and the conditions may require bracing.</p>
			<p>3. SK IV trips are suitable for advanced paddlers who have experience with steep wind waves, strong wind (~15 knots), paddling in strong currents, and crossing strong eddylines. Paddlers should be experienced paddling in rough conditions and have considerable stamina. Although it is not required, the river is one of the best places to develop rough water skills, including a brace and combat roll. In addition to re-entry techniques, conditions may require anticipatory leaning, reflexive bracing, using the paddle to stern rudder, and the ability to read moving water.</p>
			<p>This rating system gives a good idea of the skill level needed for a kayaker to go on a trip without more experienced companions. The presence of more experienced companions with good judgment can allow a relatively inexperienced paddler to participate safely in a trip, even though the rating system might indicate that the trip is ãtoo difficultä. A general guideline might be that inexperienced paddlers should be paired with experienced paddlers on trips in the moderate to exposed categories. Such considerations are the responsibility of the trip coordinator, and depending on anticipated weather or other conditions, the trip coordinator may decide that a person's experience is inadequate for a planned trip. The trip coordinator may also decide the anticipated conditions allow a relatively inexperienced paddler to undertake a more advanced trip. In making this judgment, the trip coordinator should take into consideration the expected weather, time of year (off season should indicate greater caution), overall strength of the party, and other factors such as the physical condition and stamina of the paddler.</p>
			<h3>Part 2: Planning a Trip</h3>
			<p>A) A minimum of three boaters per trip is required with at least one person chosen as the trip coordinator. The trip coordinator must be either a person listed on the ocean touring coordinator list (see Section III and the Sea Trip Coordinators List) or a person approved by the president or knowledgeable club member designated by the president or SK trip review committee on a case-by-case, prior approval basis. Factors which will be considered in such cases include the experience of the trip coordinator, the rating of the proposed trip, the expected weather conditions, whether or not the trip is planned during the off season, and overall group experience.</p>
			<p>B) Signing out the ocean touring kayaks (or any other club equipment) for more than three days is allowed only with permission from the president or equipment manager.</p>
			<p>C) Selecting a Destination: In addition, the weather forecast, predicted tide current strength and other related factors should be considered in relation to the abilities of the participants. Current marine forecasts can be obtained by using a weather radio designed to receive the continuous broadcasts of NOAA. Marine forecasts are also available by calling Weather Service Forecast and Administration at 526-6087. Tides and tide current information can be obtained from any of several published tide tables. The level of the tide is usually not as important as the current, so use a table which includes current information. The club web site has a page of weather links to some online weather and tide information.</p>
			<p>D) Trip Check Sheet: Prior to going on a trip a trip coordinator will submit a check sheet by email to the trip review committee (Part 5) The check sheet shall include information on the route, fetch distances, crossing lengths, alternate routes, time of max currents and slack, the flow of the maximum currents, and any known hazards.</p>
			<p>E) Trip Size: There is at least one trip coordinator per trip. A large party may, however, be broken up into smaller groups each with its own trip coordinator. Very large parties of 15 or more paddlers are discouraged due to the difficulties of organizing so many people, but the trip size is limited only by what the trip coordinator feels is appropriate for the current trip.</p>
			<p>F) Trip Coordinator Authority: The trip coordinator has the authority to exclude someone from a trip if in the coordinator's judgment, that person cannot safely participate.</p>
			<p>G) Trip Coordinator Responsibilities: The trip coordinator makes sure there is adequate group safety equipment, and that a trip sheet is properly filled out before departure. The trip coordinator is responsible for briefing people on basic safety and conditions particular to the excursion as appropriate, and for providing instruction as needed. Additional responsibilities include obtaining a current marine weather forecast for the trip location, reassessing the conditions on arrival at the put in and canceling or changing the destination if conditions warrant. The trip coordinator should be aware of the abilities and comfort levels of the other members of the trip. If the conditions make any member of the party uncomfortable, appropriate action should be taken to prevent the situation from becoming dangerous. This might include returning to the starting place if possible, or simply getting ashore.</p>
			<h3>Part 3: Equipment</h3>
			<p>A) Ocean Touring Safety Pack: The trip coordinator is responsible for bringing a safety pack containing:</p>
			<ol>
				<li>Emergency signaling devices, such as flares</li>
				<li>Compass and up-to-date chart of area</li>
				<li>Breakdown paddle</li>
				<li>Towline</li>
				<li>Repair kit for minor repairs (day trip) or more major repairs (extended trip)</li>
				<li>Basic first aid kit</li>
				<li> A VHF radio is recommended for SKIII or higher trips.</li>
			</ol>
			<p>B) Individual Equipment: Each trip participant is responsible for making sure they have the following equipment and that it is in good repair.</p>
			<ol>
				<li>Adequate flotation in both ends of their boat.</li>
				<li>Approved Personal Floatation Device (PFD)</li>
				<li>Paddle</li>
				<li>Sprayskirt</li>
				<li>Capsize recovery gear: Paddle float, deck rigging for paddle float rescue, bilge pump.</li>
				<li>Whistle attached to PFD</li>
				<li>Emergency signaling devices such as flares.</li>
				<li>Wet suit or dry suit and paddling jacket. May or may not be worn depending on conditions. Trip coordinator may require these be worn.</li>
				<li>Adequate clothing, including a hat for sun or cold protection, gloves or pogies, sweater, wading footgear, and dry clothing for use in the event of a capsize.</li>
				<li>Enough water. Water is often not available at destinations.</li>
				<li>Lunch or other appropriate food</li>
				<li>Sea sock. Required for a boat without one or more bulkheads when the corresponding float bags are not in use or are not secured in place. May be required, at the trip coordinator's discretion, for other boats on exposed paddles.</li>
				<li>Waterproof bags for storing any items which must stay dry, such as spare clothing. An inexpensive system is to put things into two layers of plastic garbage bags, and enclose this in a cloth bag to protect the plastic bags from tearing and punctures. Dry bags are a more expensive but more convenient and robust alternative.</li>
			</ol>
			<h3>Part 4: Group and Individual Safety</h3>
			<p>A) General Ocean Touring Safety: Safe ocean touring requires several different types of skills. Randel Washburne, in his book "The Coastal Kayaker's Manual" describes four concentric rings of defense.</p>
			<p>1. The outermost ring involves avoiding trouble in the first place, by learning about the way tide currents, weather conditions and other factors affect paddling conditions. Also included in this ring of defense would be learning how to see dangerous conditions in time to avoid them. A tide rip, if seen in time, can often be avoided by paddling in the correct direction. Pre-trip planning will indicate the best times to traverse areas with particularly strong tide currents. A study of the local weather patterns can allow the anticipation of strong afternoon winds in areas where heating of the land produces them. Since this outermost ring allows the paddler to avoid trouble in the first place, it should not be neglected in favor of the inner three.</p>
			<p>2. If the outermost ring fails (or you like to paddle in rough conditions), the next ring involves capsize avoidance in rough conditions. The important skills in this ring of defense are the boat handling skills common to all kayaking: bracing, handling waves, wind etc. These skills should be practiced by all kayakers. Whitewater boaters routinely paddle in conditions which require them to practice capsize avoidance skills. Since sea kayakers often do not, they should form a habit of practicing bracing skills whenever they paddle. A solid reflexive brace is one of the best capsize prevention skills a sea kayaker can posses. Even better is to practice in rough conditions in a safe location so that the reflexive bracing skills are tested by real conditions.</p>
			<p>3. The next ring of defense involves recovery from a capsize. By far the best method for this is the eskimo roll. No other capsize recovery method is as rapid. It is important to realize that them may be conditions under which an eskimo roll fails. In such circumstances, it is imperative to be able to perform some other method of capsize recovery. A point worth stressing is that the paddler will be much more likely to succeed in reentering a kayak if dressed for immersion in the anticipated water temperatures.</p>
			<p>4. The final ring of defense involves signaling for help. Needless to say, if a situation gets to this point, the paddler is in extreme danger. Methods for attracting potential rescuers involve signaling devices, such as flares and marine VHF radios. Depending on the location, and difficulty of the trip, any or all of these methods might be used. As an absolute minimum, a kayaker should carry flares on any trip. Without such aids it can be extremely difficult or impossible to attract attention since a kayak is small and not easily seen, especially in the conditions under which an accident is most likely to occur.</p>
			<p>B) Group Management Guidelines: A number of procedures should be agreed on for travel in a group. The trip coordinator should discuss these with all trip participants.</p>
			<p>1. The group should stay together. If paddlers are of widely different strength, the slower paddlers should not be left behind to fend for themselves. Depending on conditions, a ãfastä and ãslowä group might be allowable, but there must be a clear understanding of the route and planned meeting place by all involved. In adverse conditions, it is important that the whole group stay within voice communication distance. It can be extremely difficult to regroup if a party is separated without a clear meeting place arranged. In a large group, pairing experienced with inexperienced paddlers will help to keep the group together, and provide the less experienced with assistance if difficult conditions arise.</p>
			<p>2. The day's plans should be discussed before departure. The trip coordinator should take advantage of this to help less experienced participants learn about pre-trip planning. Contingency plans should be discussed, so that a minimum of discussion is necessary if the contingency plan is needed.</p>
			<p>3. A set of signals should be understood by all members of the party. Visual signals are those of the American Whitewater Association: STOP is indicated by holding the paddle horizontally over the head, and moving it up and down. HELP or EMERGENCY is signaled by holding the paddle vertically and waving it from side to side. COME AHEAD is indicated by holding the paddle vertically, without waving it. If a particular course is to be indicated, the paddle should lean toward the desired course (this might be used in directing someone through surf, for example).</p>
			<p>4. All group decisions need to be made with the experience and ability of the weakest member of the party in mind. Experienced paddlers should remember that conditions which seem easy to them may well cause an inexperienced paddler to capsize. All kayakers would do well to remember that a capsize situation is much more serious in the ocean than it usually is on a river or lake. On the ocean, the option of taking the swimmer ashore is rarely feasible.</p>
			<h3>Part 5: SK Trip Review Committee</h3>
			<p>The trip review committee is to be composed of all SKIII trip leaders and above for the purpose of reviewing trip sheets submitted by any leader of an upcoming trip. Trip sheets should be submitted well in advance to allow proper review and discussion, particularly for SKIII level trips and above. All current leaders (III and above) will be placed on the list unless they indicate a desire not to be a part of this process (this will include leaders who have been approved and advance to SKIII; in other words, they will be automatically added to the list upon advancement unless they express the desire not to partake). If there are suggestions a trip review member would like to make to point out trouble spots or describe encounters that one has had regarding the proposed route, people involved, etc., the suggestions should be sent only to the trip leader and not to the entire trip review committee. If a member of the trip review committee has a problem regarding the proposed trip, that member should email these concerns to the coordinator and the rest of the trip review committee for discussion. If these concerns are considered substantial by a majority of other committee members who have taken the time to review the proposed trip in some detail, then modifications of the trip may be required, such as re-routing, shortening, adding experienced people, etc. This would ultimately be decided upon by the safety committee. NOTE: There is never a desire to prevent a proposed trip from happening, only that it proceeds as safely as possible without too much restriction.</p>
		</div>
		
<?php require("../inc/bottom.php"); ?>		