<?php require("../inc/top.php"); 
?>
		<div id="main">
			<?php require("../inc/subnav_lake_polo.php"); ?>
			<h1>Lake Washington Rules</h1>
			<p>The University has a fleet of kayaks available for club member use on Lake Washington and many of you have joined the club to take advantage of this great resource. In making these boats available, everyone has a responsibility to observe some basic but important safety precautions. Please remember that you must be a club member to use our boats (friends on campus can join the club, folks from off campus can rent a boat from one of the local outfitters including WAC rentals which has canoes).</p>
			<p>First, make sure you fill out a Yellow Card. This is important to document use of club gear and is important for making decisions regarding gear purchase and university funding. As you leave the WAC and get ready to launch your boat, make sure you are wearing a life jacket that is snugly buckled and zipped, not just loosely hung over your arms.  Wearing a wetsuit will provide additional buoyancy as well as insulation in case of a swim.</p>
			<p>Whitewater boats work best with shorter paddles (under 210 cm), while sea kayaks are used with longer paddles.  Similarly, different spray skirts fit different groups of boats.  You should have received an orientation to which groups of gear go with which boats when you joined the club.  If you are uncertain, please attend another pool session or ask the officers.  You may use the club paddling jackets when it is raining, but do not use the dry tops (with black latex rubber wrist and ankle gaskets) unless you are practicing rolls, since the gaskets are uncomfortable and also rip easily.</p>
			<p>When on the lake, we recommend that you paddle with a buddy. Other outfitters on the lake (NWOC, Agua Verde) do make kayaks available for individual paddlers and our boats are also available in this manner but paddling with a buddy provides an additional measure of safety.</p>
			<p>Boats should only be used on the lake when the WAC is open. If you are paddling during hours that the WAC is not open then you must follow the guidelines for a club trip (a minimum of three boats and an approved trip coordinator). You are not allowed to paddle after sunset unless part of a club trip.</p>
			<p>Once you have completed the wet exit test and annual membership paperwork, you may take any of the river or sea kayaks out on the lake.  If you do not have prior kayaking experience, you should first ask for instruction at a pool or lake session in the basics of kayaking: forward stroke, sweep stroke, edging and bracing.   It is STRONGLY recommended that you remain very close to shore until you take a rescue skills clinic (these are typically informally organized by sending an email to the sea kayak trip coordinator list: ukc-skl).  This is particularly important during the months of October through May, when the lake is coldest and there are fewer other boaters out who might be able to assist you.</p>
			<p>Make sure that you have float bags. Some of our boats will sink without flotation. An inflated float bag is an essential piece of safety gear. They are typically removed from boats during storage, but must be used when paddling on the lake.  The only exceptions would be some of the newer sea kayaks with two-piece hatch covers.  If a boat looks old, has single-piece hatch covers or is a river boat, it is likely to sink without float bags.</p>
			<p>We allow you to take boats throughout Lake Washington, but use careful judgement when venturing out beyond the immediate WAC area. One of the greatest dangers on Lake Washington, particularly during the winter months, is hypothermia. Wet suits are available for your use when the water is cold (most of the year!) and provide an additional layer of safety.  Without a wetsuit, swimmers can become helpless or drown within minutes.</p>
			<p>If you are just learning, stay within the relatively protected waters of the Arboretum or paddle along the shore. This is also the best way to avoid large boat traffic. Travel through the Montlake Cut is not advised unless you have a strong set of skills. Waves from boats can create a significant hazard in the Cut, particularly when several powerboats are traveling through at the same time.</p>
			<p>Finally, we have two fiberglass boats that require a more advanced skill set. These are the Impulse (a sea kayak) and the downriver race boat. If you have not received training in these craft please do not use them. If you have any questions regarding use of our more specialized boats please do not hesitate to contact the appropriate interest group tzar.</p>

		</div>
		
<?php require("../inc/bottom.php"); ?>		
