<?php require("../inc/top.php"); 
?>
		<div id="main">
			<?php require("../inc/subnav_whitewater.php"); ?>
			<h1>River Rating Scale</h1>
			<p><img class="left" src="imagelib/class_1.jpg" alt="Typical Class I river"><strong>Class I:</strong> Easy. Fast moving water with riffles and small waves. Few obstructions, all obvious and easily missed with little training. Risk to swimmers is slight; self-rescue is easy.</p>
			<br clear="all" />
			<p><img class="left" src="imagelib/class_2.jpg" alt="Typical Class II river"><strong>Class II:</strong> Novice. Straightforward rapids with wide, clear channels which are evident without scouting. Occasional maneuvering may be required, but rocks and medium sized waves are easily missed by trained paddlers. Swimmers are seldom injured and group assistance, while helpful, is seldom needed. Rapids that are at the upper end of this difficulty range are designated "Class II+".</p>
			<br clear="all" />
			<p><img class="left" src="imagelib/class_3.jpg" alt="Typical Class III river"><strong>Class III:</strong> Intermediate. Rapids with moderate, irregular waves which may be difficult to avoid and which can swamp an open canoe. Complex maneuvers in fast current and good boat control in tight passages or around ledges are often required; large waves or strainers may be present but are easily avoided. Strong eddies and powerful current effects can be found, particularly on large-volume rivers. Scouting is advisable for inexperienced parties. Injuries while swimming are rare; self-rescue is usually easy but group assistance may be required to avoid long swims. Rapids that are at the lower or upper end of this difficulty range are designated "Class III-" or "Class III+" respectively.</p>
			<br clear="all" />
			<p><img class="left" src="imagelib/class_4.jpg" alt="Typical Class IV river"><strong>Class IV:</strong> Advanced. Intense, powerful but predictable rapids requiring precise boat handling in turbulent water. Depending on the character of the river, it may feature large, unavoidable waves and holes or constricted passages demanding fast maneuvers under pressure. A fast, reliable eddy turn may be needed to initiate maneuvers, scout rapids, or rest. Rapids may require "must'' moves above dangerous hazards. Scouting may be necessary the first time down. Risk of injury to swimmers is moderate to high, and water conditions may make self-rescue difficult. Group assistance for rescue is often essential but requires practiced skills. A strong Eskimo roll is highly recommended. Rapids that are at the upper end of this difficulty range are designated "Class IV-" or "Class IV+" respectively.</p>
			<br clear="all" />
			<p><img class="left" src="imagelib/class_5.jpg" alt="Typical Class V river"><strong>Class V:</strong> Expert. Extremely long, obstructed, or very violent rapids which expose a paddler to added risk. Drops may contain large, unavoidable waves and holes or steep, congested chutes with complex, demanding routes. Rapids may continue for long distances between pools, demanding a high level of fitness. What eddies exist may be small, turbulent, or difficult to reach. At the high end of the scale, several of these factors may be combined. Scouting is Recommended but may be difficult. Swims are dangerous, and rescue is often difficult even for experts. A very reliable Eskimo roll, proper equipment, extensive experience, and practiced rescue skills are essential. Because of the large range of difficulty that exists beyond class IV, Class 5 is an open ended, multiple level scale designated by Class 5.0, 5.1, 5.2, etc... Each of these levels is an order of magnitude more difficult than the last. Example: Increasing difficulty from class 5.0 to class 5.1 is a similar order of magnitude as increasing from class IV to Class 5.0</p>
			<br clear="all" />
			<p><strong>Class VI:</strong> Extreme and Exploratory. These runs have almost never been attempted and often exemplify the extremes of difficulty, unpredictability and danger. The consequences of errors are very severe and rescue may be impossible. For teams of experts only, at favorable water levels, after close personal inspection and taking all precautions. After a Class VI rapids has been run many times, It's rating may be changed to an apppropriate Class 5.x rating.</p>
			<p>From the American Whitewater Safety Code, adopted 1959, revised 1998</p>
			<p>Now, a few words about all this rating stuff. The rating system is an attempt to reduce the complex and infinitely varied features of all the rapids on the planet to one of six categories, and as such, it has its limitations. Knowing that a rapid is class III, for instance, does not tell you all you need to know to run it. The only real way to assess the difficulty/danger of a rapid is to learn how to read the water, and then go look at it yourself. The advice of guidebooks and of other experienced paddlers can be invaluable; but in the end, the decision to paddle or portage is a highly personal one that everyone who runs whitewater should learn to make.</p>
			<p>A common question about upper end of the scale is "Does a successful run of a previously 'unrunnable' rapid make it a class VI, rather than 'unrunnable'?". The answer is no. Various expert paddlers with a certain cavalier attitude have managed drops such as Ohiopyle Falls on the Yough, but it is probably better for our collective health to continue to consider those places out-of-reach. Even though techniques and equipment continue to improve, bringing more rapids into the "runnable" category, we need to be very careful about devaluing ratings -- especially in rapids where there is significant danger.</p>
		</div>
		
<?php require("../inc/bottom.php"); ?>		