<?php require("../inc/top.php"); 
?>
		<div id="main">
			<?php require("../inc/subnav_whitewater.php"); ?>
			<h1>Whitewater Safety</h1>
			<h2>Part 1: Planning a trip</h2>
			<p>A) Organizing a Trip: A whitewater paddling trip consists of at least three UKC River/Sea Members, with at least one person who is a qualified trip coordinator. A river trip may be organized by a group prior to the departure date, or formed from interested paddlers who arrive at the WAC at the appropriate time for loosely scheduled trips. As a rough guideline, consider a 1:2 ratio, or larger, of experienced to less experienced boaters, where experience is defined relative to the difficulty of the water to be attempted. This ratio may change depending on the total number of boaters in the party and their range of expertise.</p>
			<p>B) Trip Coordinator Designation: The trip coordinators are designated by the group and identified by being listed on the appropriate line of the trip sheet, which must be filled out before each river trip. The trip coordinator must be approved by the club for the class of water involved, see Section III. The WW Trip Coordinator List is available in the club web site.</p>
			<p>C) Selecting a River: The skills of the weakest paddler and the number of weak paddlers carry the most weight in the decision of what river to paddle. Refer to the Permitted River List, in choosing a river. Another consideration is the expected water level. It is good to have a reasonable alternative river in mind given that river conditions are always somewhat uncertain. Often, you can find out the river level by using the world wide web or by calling the Whitewater Hotline (526-8530). The American Whitewater StreamKeeper project has extensive information on flow levels. The trip coordinators have final say about river selection.</p>
			<p>D) River Trip Size: There may be more than one coordinator per trip, however for organizational efficiency on and off the river, a single lead coordinator may be designated. A large party may also be broken up into smaller groups each with its own set of experienced paddlers. Very large parties of 15 paddlers or more are discouraged due to the difficulties of organizing so many people, but the trip size is limited only by what the trip coordinators feel is appropriate for the current trip.</p>
			<p>E) Trip Coordinator Authority: Each paddler must make their own final decision on whether to run a particular river or rapid. The trip coordinator has the authority to exclude someone from joining a trip, or running a rapid even if the paddler believes they are up it. The decisions of the trip coordinators are final.</p>
			<p>F) Trip Coordinator Responsibility: The trip coordinator makes sure that there is adequate group safety equipment (throw ropes, breakdown paddle, first aid kit), and that a trip sheet is property filled out before departure. At the put-in, the trip coordinators should quickly assess the paddling level and experience of each paddler, and arrange for pre-river briefing as is appropriate. On the river, the trip coordinator, or an experienced paddler designated by the coordinator, should keep a look out for the weaker paddlers, providing skills instruction and information on specific rapids as needed. The trip coordinator may designate other experienced paddlers in the group to assist with instruction, and may, when appropriate, designate a single sweep boat. This sweep boat is generally the last one down a rapid, and provides rescue assistance. The coordinator works to maintain group safety by trying to assist boaters in acting responsibly (see Part 3, Team Safety).</p>
			<h2>Part 2: Equipment</h2>
			<p>A) Personal Safety Equipment: Each trip member is responsible for making sure that they have all the appropriate equipment, and that it is in good working order. If you find broken or damaged gear in the clubroom, put it in the to-be-repaired bin. For a river trip, each paddler must have a helmet, PFD, and suitable body wear (e.g., wet suits, dry suits, warm clothing). These items are essential. Thus, without them you may not run the river. Each paddler is responsible to assure that these items are appropriately marked on the trip sheet, either designated as club or personal gear.</p>
			<p>B) Boat Equipment: Adequate flotation, as defined by paddler experience and type of boat, is needed in all boats that are taken on the river. Decked boats require at least two stern float bags, with possibly two additional float bags for the bow. Open canoes require bow and stem bags, with an optional middle bag. Check bags for leaks prior to departure from the WAC. Each kayaker should check their boat to ensure that the foot pegs can be properly adjusted, and that there is appropriate padding for a good fit. Each paddler is responsible for signing out his or her equipment on the trip sheet. Identify boats by number and briefly describe paddles and other equipment.<p>
			<h2>Part 3: Team Safety</h2>
			<p>A) Upstream Right of Way: The boat in the current (typically the upstream boat) has the right of way on the river. For example, a boater playing in a hole at the bottom of a drop should yield to upstream boaters approaching the drop. Also, when you eddy out, be aware of upstream boaters who may need to use that eddy. If necessary, exit it soon enough so that the upstream boaters can be aware of its availability and paddle to it.</p>
			<p>B) Communication: Communicating on the river may be difficult over the roar of the water and as a result of the distance between the top and bottom of a particular rapid. Standard paddle signals have been developed to ease communication. Stop is indicated by a horizontal paddle raised over the head. Eddy out immediately and wait for further information. An emergency is indicated by a waving vertical paddle. A stationary vertical paddle indicates that it is safe to proceed. The paddle may be pointed slightly to one side or the other indicating the recommended direction or side of the river to be on while going down the rapid. When giving verbal instructions, state directions or places to go, and not what or where to avoid, unless you are certain that people receiving the information can clearly hear the qualifiers (generally only during discussion on shore).</p>
			<p>C) Following: Often, a less experienced paddler, because of unfamiliarity with a stretch of river or less-developed river reading skills, will want to follow another boater down a rapid. The less experienced paddler must make an explicit agreement with the more experienced paddler so that the leading paddler is aware that someone is following. Otherwise, the more experienced paddler might inadvertently lead the other into a difficult situation, or to a play spot the less experienced paddler had no intention of going.</p>
			<p>D) Boat Spacing: Experience will teach a paddler the appropriate spacing on the river. The spacing will vary depending on the river flow rate, width of the river channel, presence of eddies, and skill level of the boaters. Use eddies to reestablish proper spacing between boats when they get too close. Spacing that is too great makes signaling for help difficult in an emergency. Following too close can result in spearings or collisions when the lead boat is caught in or slowed down by holes. When closely approaching and overtaking another boat, be sure to give a shout, alerting the other boater to your presence.</p>
			<p>E) Keep Count of Upstream Boaters: Make frequent counts of the number of boaters in your group, noting the number of boaters upstream of you, and those that are downstream.  Loosely following some order of proceeding down drops, which is either assigned or evolves, may help prevent straggling behind or unnoticed accidents. If the trip coordinator has designated a lead boat and a sweep boat, it is advantageous for all paddlers to respect, to the extent that a paddler is able to under a given situation, these positions of first and last down the river.</p>
			<p>F) Spearing: Watch your bow point when entering an eddy occupied by another boater. Enter occupied eddies under control and only if there is room.</p>
			<p>G) Occupying an Eddy: If a second boat is about to enter your eddy, make room or signal that there is not enough room for another boat. Draw strokes can be helpful in maintaining your position in an eddy.</p>
			<p>H) "Hole Etiquette:" Respect the order of boats lined up for a play hole or wave. Signal and watch for acknowledgment when lines form on both sides of the river above or below a play hole. If two boats unintentionally enter a hole at the same time, practice defensive boating and yield. At the very least, communicate loudly with the other boater (e.g., "on your right").</p>
			<p>I) Scouting: Scouting rapids is required when the trip coordinator deems it necessary. Individuals may want to do additional scouting. Notify others when you alone hold up for scouting.</p>
			<p>J) Swimmers: If a person swims, first go after the boater. If the rescue of the swimmer is under control, then chase down whatever equipment may be floating around. Do not let the swimmer or the floating gear distract you from the fact that you are still on a river. Remember to look downstream, and plan your route. Do not endanger yourself or complicate the situation by attempting a rescue in a rapid where you are not comfortable. If you are not involved in the rescue process, then eddy out where possible and wait for everyone to re-group.</p>
			<p>K) Rescuing a Swimmer: (Boat Rescue) In rescuing a swimmer, it is best to approach from the upstream side with your stem towards the swimmer. The swimmer should be upstream of the loose boat, holding that boat's grab loop and paddle with one hand and reaching for the rescue boat's stem grab loop with the other hand. The swimmer should never stick fingers or hands through the grab loop due to the risk of breaking fingers or entrapping the hand. Attempt to get the swimmer to the side quickly, but take the time to look ahead and plan your route. Find a good eddy that you can reasonably get to. Remember that it will be a lot harder to make eddies with extra weight dragging on the back of your boat. The swimmer should frog kick or side stroke kick to assist the rescuer. Try to keep your swimmer calm. Talk to the swimmer when possible, but remember that communication is difficult in the roar of the water. Sometimes it is best to just have them hold on and rest until you get to the bottom of the rapid, and then paddle and swim (do not let them forget to help you by kicking) to the side. The rescuer may tell the swimmer to let go of the rescue boat grab loop if a serious drop is approaching that cannot be avoided. The swimmer must let go to avoid being speared by the rescue boat and to allow the rescue boat to maneuver in the rapid before repeating an attempt at rescue. The rescuer may request that the swimmer let go of the loose boat to better assure the swimmer's swift rescue. This may be advantageous if there are other paddlers available to retrieve the boat.</p>
			<p>L) Rescuing a Swimmer: (Shore Rescue) A swimmer may be rescued from shore with the use of a throw rope. People practiced in the techniques of using a throw rope, may be placed at strategic locations in or below difficult rapids. These people wait on shore with a throw rope ready in hand and watch for swimmers needing assistance.</p>
			<p>M) Rescuing a Pinned or Entrapped Boater: A boat that is 'pinned' is stuck in a stationary position on the upstream side of a log, rock, or other immobile object in the river. The force of the water compresses the boat against the obstruction. An entrapped boater is a person caught in the pinned boat. This can occur when the force of the water bends the boat downstream of the object, wrapping the boater's legs. Entrapment may also occur when a swimmer's foot is wedged between rocks on the river bottom, or is caught on a submerged tree branch. The rescue of such a person can involve a complicated series of maneuvers. The designated trip coordinator acts as the rescue coordinator or assigns this duty to an appropriate person. The situation should be assessed and the most appropriate action to take determined. The type of action will be based upon the victim's condition which should be addressed first, and the extent of risk to the rescuers. To learn river rescue techniques, you are encouraged to read various books and take classes on the subject. The club has several books and videos that are available for check out, most notably, 'River Rescue'. River safety manuals published by the American Canoe Association are also available for reading. The club organizes rescue practice sessions and review of techniques. It is advised to discuss and practice rescue techniques as often as is practical.</p>
			<p>N) Briefing at Put In: The trip coordinator should determine the need and extent of any briefing before paddling the river. Paddle signals, river conditions and boat order for proceeding down drops may be briefly reviewed at the put-in. Basic personal safety (e.g. how to safely swim and be rescued) and basic river reading and terminology (e.g. rocks, eddies, current) should be discussed with beginners, especially those who have not previously been on a UKC river trip. Basic whitewater techniques (how to avoid flipping, moving in and out of current) may also be discussed with beginners on shore, or at appropriate places on the river. It is the responsibility of each paddler to ask any questions, or raise any issues about the river conditions that might put into question a boater's ability or comfort in paddling the proposed stretch of river.</p>
			<p>O) Order, Eager Beavers and Stragglers: Do not straggle behind; keep up with the group. Respect order in passing down drops: usually, the trip coordinator first and if designated, the "sweep" boat last. The sweep should carry a breakdown paddle and a throw rope. Should the group become spread out over a long rapid, a less experienced boater should make an effort to stay nearby one or more boaters.</p>
			<p>P) Wait Up for Stragglers: If you are the second to the last boater and the last boater does lag behind (straggler, emptying boat, cramps or anything), hold up in an eddy and wait. Signal others downstream of you to wait up.</p>
			<p>Q) Buddy Support: Be supportive of learning and intimidated boaters.</p>
			<p>R) Speak Up About Safety: If you observe unsafe activities or procedures, you contribute to continuing the lack of safety by "keeping it to yourself". Confront the person acting unsafely or at least speak with the trip coordinator.</p>
			<h2>Part 4: Personal Safety</h2>
			<p>A) Too Much, Too Fast: Boating a river, and the individual rapids on that river, is ultimately a personal decision, not a group decision. Ask yourself if you are willing to cope with the water if things do not go well. If your boating becomes primarily a constant test of guts, you are probably biting off too much too fast. No matter how strong the group or coordinators, you are alone in your boat. In whitewater boating, bigger may not be better. Ask yourself who you are trying to impress</p>
			<p>B) River Choice for Users of Club Equipment: For those using club equipment, your choice of river difficulty has implications for not only your safety but the club's survival as well. Consequently, for users of club equipment, river choice must be more conservative than if private equipment were used.</p>
			<p>C) Strainers: A strainer is anything in the river that lets water pass through, but will not let a boat pass, for example, a partially submerged tree. The force of the river that holds you against a strainer is incredibly strong. Strainers are much more dangerous than rocks in the river, since the current always flows around the rock and may push your boat with it. Stay well away from any strainer if at all possible. Be aware of river conditions in which strainers may be created: narrow river channels, previous storm or flooding conditions. When paddling with a watchful eye, strainers are often easily spotted and avoided. If you do wash up against one, LEAN DOWNSTREAM QUICKLY onto the obstruction or strainer. Then signal for help. With help at hand, attempt to work yourself to clear water. Wet escaping from your boat when pinned may be necessary but this is a LAST resort. Popping the spray-skirt and filling the boat with water will usually increase the possibility of entrapment in the boat.</p>
			<p>D) Rock and Headwall Rolls: Often found on tight rivers, a wall is a steep section of riverbank where the river runs head-on into it. Paddle clear of headwalls, providing enough space to not allow the current to push the boat into it. Flipping upstream of a headwall is to be avoided, but may happen. Rolling up against a headwall or rock is a tough act, but rolling up to the downstream side is the way to go. The downstream side will be the rock side. Using your paddle may be awkward in such cases. Climb up the rock or wall with your hands to a downstream lean position and move yourself to safety. To repeat, the best safety tip concerning head walls is to avoid them. Undercut headwalls can be deathly serious, in which you may need to swim straight down and then out, hoping to get washed out by the current.</p>
			<p>E) Whirlpools: Getting set up for a roll when capsized in a whirlpool is not a simple task. Moving the paddle around under water becomes very difficult. The downstream edge of your boat is constantly changing and is found more by chance than anything else. Observation of whirlpools will show, though, that they dissipate and periodically reform. Thus, the best strategy is often to wait, hoping to get washed out or to roll during a momentary canning of the water.</p>
			<p>F) Variable River Difficulty. Flow levels and water and air temperatures affect the difficulty of a particular run. A particular rapid at a low flow rate can increase in difficulty by one or more class level ratings at higher water levels, when the water may be more 'pushy' and the consequences of a paddling mistake may be quite serious. Colder temperatures can increase paddler fatigue and exhaustion, especially in the case of a swim.</p>
			<p>G) Swimming: In a swim, keep your FEET UP high near the surface of the water, AND DOWNSTREAM. Never walk on the bottom, crawl out of the river when you are in slow flowing, shallow water near the bank. The danger in moving water is pinning a foot between rocks and getting knocked over by the current. You may have the strength to hold yourself out of the water for a few moments, however, your body will relax with your head under water in the "resting" position. When swimming, try to hold onto all of your equipment, but if your safety is in question, then let go of it. Stay upstream of your boat if possible. Always be looking ahead to avoid possible entrapment situations. You can often use a backstroke or sidestroke to swim to an eddy or to shore. At times, you may want to wait until the end of the rapid before trying to get to shore. In that case, the best strategy may be to conserve your body heat and strength by simply wrapping your arms around your chest and floating down stream keeping yourself as relaxed as possible. Let your fellow paddlers come to you. If you are passing through rough water, relax and concentrate on the timing of a good breath of air when one becomes available.</p>
			<p>While swimming in rough water, you may find yourself approaching a hole or reversal. Letting go of your boat when trapped in a large reversal may be necessary, although often you will wash through holes created by reversals. Generally, letting go of your paddle when you are stuck in a reversal is not a good idea. This is a controversial subject. However, letting go of your paddle when in a strong reversal leaves you helpless like a cork. The only option then may be to swim toward the bottom of the hole in an attempt to catch a downstream flowing jet of water. Keeping your paddle may help you catch such a jet more easily or may help you in working out the side of the hole.</p>
			<p>When a paddler approaches you for a rescue, listen to their instructions. Grab the stern (back) loop on the rescue boat as soon as possible, and always without putting either your fingers or hand through the loop. The goal is to get you out of the water as quickly as possible without compromising either your or the rescuer's safety. Assist the rescuer by kicking, and by letting go of either your boat or theirs when told to do so. A swimmer may also be rescued with the use of a throw rope. If a rope is tossed to you, grab the bag, knot or whatever is on the rope-end as quickly as possible. Hold the rope with it on your chest, so that you are floating on your back with your feet up. This is the safest position to be pulled over the water, because an air pocket is created by the head. Should the rope become caught, and your safety placed in danger, let it go immediately.</p>
			<p>H) Paddling in Holes: Many holes and small reversals can be 'punched' by paddling very strongly and swiftly through it. However, all boaters find themselves caught in a hole at sometime or another. Lean downstream and onto a brace. The pillow of water formed by the reversal hydraulic will support a pretty heavy brace or roll sweep stoke. In most situations staying in your boat when you flip over in a hole is a good choice as rolling up onto a downstream brace on the reversal wave is not as difficult as it may appear to be. Rolling up onto the upstream side of the hole is difficult and unstable. If the downstream side is your offside and you do not yet have the offside roll, try putting the paddle out at right angles to the, boat to the downstream side. The surface current may catch your paddle and roll you up. The undercurrent may also catch the body of an overturned paddler and push both paddler and boat out of the hole to calmer water where rolling on either side would be effective.</p>
			<p>There is the choice of bracing or rolling when you are tipped in a hole, and it is worthwhile to realize that awkward and shoulder-damaging braces occur very easily. Do not extend your arm back behind the plane of your body or over your head. Rather than struggle with an overextended brace, drop into the roll position and see how easily you will roll up. Once upright with a delicately balanced downstream lean (not usually an extreme downstream lean) the next step is to work your boat toward one end of the hole where it will push either your stem or bow out. This is accomplished with sculling strokes.</p>
			<p>Advanced boaters may purposefully drop into a hole for practice or for play. Note that in riding a hole, very little bracing may be required. The key is to move your boat with subtle hip action feeling yourself actually sitting on (or slightly upstream of) the whitewater crest of the surfing wave, weight slightly shifted in a downstream lean, with the trunk of your body as upright and vertical as comfortable. Quick moves to cut back laterally across the face of the wave are made most easily by first riding up on the wave crest so that it is right beneath your buttocks and the bow and stem points are clear (or nearly clear) of the water.</p>
			<p>I) First Aid and CPR: Learn or refresh your understanding of first aid and CPR. The University of Washington/IMA and the Red Cross have regularly scheduled classes, and in the past the club has occasionally sponsored classes as well. All paddlers are encouraged to have current basic first aid and CPR certifications.</p>
			<p>J) Physical Fitness: Generally good physical conditioning supplemented with some weight work can prevent many injuries, particularly shoulder injuries. Consult books and articles (some relevant articles are kept in the club 'library') which discuss appropriate muscle development and exercise. Lake paddling is a good tune-up for a river trip if you have been away from the sport a while, and an opportunity to develop proper paddling technique. The way you paddle can go a long way towards reducing the danger of shoulder dislocation. Avoid any motion that puts your arm up and to the back relative to the trunk of the body. Keep your elbows low. In particular, learn to use the low brace (using the backside of the paddle kept below shoulder level) as much as possible.</p>
		</div>
		
<?php require("../inc/bottom.php"); ?>		