<?php require("../inc/top.php"); 
?>
		<div id="main">
			<?php require("../inc/subnav_whitewater.php"); ?>
			<h1>Slalom</h1>
			<h2>Overview</h2>
			<p>The UKC does not have a formal slalom team, but some club members are active participants in local races coordianted through the <a href="http://www.nwwhitewater.org/" target="offsite">League of Northwest Whitewater Racers</a>. Racing is a highly effective way of improving your technical boating skills and is a lot of fun as well. Races are typically held on class II or III rapids, but running a course typically requires skills about a grade higher than the rated level of the drop. (For this reason, slalom provides a means of obtaining difficult white water challenges without the risks of more-dangerous water.)</p>
			<p><img class="right" src="imagelib/whitewater-slalom.jpg" alt="Slalom Race on the Northfork of the Nooksack" />Most races accommodate a wide range of skill levels by including several classes for a variety of boat categories. A "Class" is three or more boats of the same type. In the men's kayak category there may be up to four classes ('novice' through 'elite'), while in the women's kayak category there may be up to three classes ('beginner', 'advanced' and 'elite'). Open and decked canoe categories typically have only a couple classes. In this way, nearly all boaters can race at a level that is both fun and challenging. Once you win a race at a particular skill class, you are expected to compete in the next higher class thereafter.</p>
			<p>Local racers, The League of Northwest Whitewater Racers, maintain the Lake Washington practice gates below highway 520 at the west end of the Lake Washington bridge. Although located on 'flat water', these are very helpful for improving maneuvering skills, and are conveniently located a few minutes of paddling away from the Waterfront Activities Center. Whether you race or not, you may find it beneficial to spend time working with these. Also, training gates are set up on the class II Cedar River at the Landsburg bridge for training on moving water.</p>
			<p>Although the Pacific Northwest boasts some world class slalom boaters, most of the local races are informal, and most of the participants consider themselves 'recreational' racers. All the races are organized and run by volunteers (often the race participants), and this fosters a high level of comraderie. Those who attend / participate discover a friendly atmosphere where all are encouraged to join in the fun.</p>
			<p>Because the races are run by unpaid helpers, we encourage all who can to contribute time and effort towards these events. Volunteers are needed the day before the race to set-up the course, to make road signs, and to help organize a variety of things. On race day, volunteers are needed as gate judges (you will be told how to do this), and to help disassemble the course and clean up after the racing ends. If you can assist in any way, or would like to learn more about a particular race, call the contact person listed for the race of interest.</p>
			<p>It is common for participants and volunteers who show up early to camp out the night before the race. This is a great opportunity to mingle with other boaters and share tales of the water.</p>
		</div>
		
<?php require("../inc/bottom.php"); ?>		